### PR TITLE
Logrus instrumentation hook

### LINKED ISSUE #47: Add support for Logrus
Add support for Logrus: https://github.com/sirupsen/logrus

### PR DESCRIPTION
**Pull request by tonyredondo**
Closes #47 

This `PR` contains a logrus hook implementation to write the logs in the span of the given context.

**Usage**

```go
	ctx := scopeagent.GetContextFromTest(t).   // Gets the test context

	logger := logrus.New()
	logger.SetLevel(logrus.TraceLevel)
	logger.SetReportCaller(true)   // Allow to report the file and line number in the log event source
	AddScopeHook(logger)  // Adds the scope hook into the logros logger

	logger.WithContext(ctx).WithField("Data", "Value").Error("Error message")
	logger.WithContext(ctx).WithField("Data", "Value").Warn("Warning message")
	logger.WithContext(ctx).WithField("Data", "Value").Info("Info message")
	logger.WithContext(ctx).WithField("Data", "Value").Debug("Debug message")
	logger.WithContext(ctx).WithField("Data", "Value").Trace("Trace message")
```

**Results**
image

### CODE REVIEW

**Comment by drodriguezhdez** [comment]
Awesome @tonyredondo 

I have a question: Can we have detect if the scope Hook was added before? To avoid adding several times.

I'm experiencing an issue in `docker/distribution` repo due to `logrus.StandardLogger()` returns a singleton, if the `docker` app is initialized several times, the hook is added those times with the following result:

image

image

**Comment by tonyredondo** [comment]
Mmm ok, I’ll make the change.

**Comment by tonyredondo** [comment]
Sorry for the delay, I've added a helper function for the problem you told me:

https://github.com/undefinedlabs/scope-go-agent/blob/logrus-support/instrumentation/logrus/hook.go#L24-L35

Just call it like:

```go
AddScopeHook(logger)  // Adds the scope hook into the logros logger
```

**Comment by tonyredondo** [comment]
@drodriguezhdez

**Comment by drodriguezhdez** [comment]
awesome. Thanks @tonyredondo !

**Pull request merged**
