### PR TITLE
.git folder parser alternative without external dependencies

### PR DESCRIPTION
**Pull request by tonyredondo**
This `PR` replace the dependency to `src-d/go-git` using a custom `.git` folder parser without any external dependencies.

image

### CODE REVIEW

**Comment by drodriguezhdez** [comment]
Can we include some tests?

**Comment by tonyredondo** [comment]
> Can we include some tests?

I'll try, it's hard because reads the `.git` folder, but I guess I can do some tests of the regexes in use, at least...

**Comment by tonyredondo** [comment]
> Can we include some tests?

Done @drodriguezhdez

**Comment by drodriguezhdez** [comment]
Checked with `go-ethereum`.
It seems `branch` is not being sending:

https://app.scope.dev/dashboard/b774c8da-2494-4ede-8d2f-b0321ff3cd7c/f9775d86-9c81-43d9-a28c-3f3cb60f30b4/default/explore/inspect/fe9cb4954f12ec9709d448d6f274c7088322eb60/00000000-0000-0000-70b3-e3e4509d0ff2/trace?spanId=00000000-0000-0000-0713-8c606cc58d21

**Comment by tonyredondo** [comment]
> Checked with `go-ethereum`.
> It seems `branch` is not being sending:
> 
> https://app.scope.dev/dashboard/b774c8da-2494-4ede-8d2f-b0321ff3cd7c/f9775d86-9c81-43d9-a28c-3f3cb60f30b4/default/explore/inspect/fe9cb4954f12ec9709d448d6f274c7088322eb60/00000000-0000-0000-70b3-e3e4509d0ff2/trace?spanId=00000000-0000-0000-0713-8c606cc58d21

Done, the `branch = HEAD` when a detached commit is being used was missing.

**Comment by drodriguezhdez** [comment]
Tested in local, with repos no containers, and with repos inside containers.
https://app.scope.dev/dashboard/b774c8da-2494-4ede-8d2f-b0321ff3cd7c/400412c1-517f-4f94-8291-7cc167d92ca4/default/explore/inspect/93645c357bde143c6275b6119fd255a8e8071287/00000000-0000-0000-69b2-30adb11f0355/trace?spanId=00000000-0000-0000-480d-57aa489125bb

Approved

**Pull request merged**
