### PR TITLE
Make our tracer play nice with other opentracing tracers

### PR DESCRIPTION
**Pull request by fermayo**
* By default, agent autoinstallation does not affect opentracing's global tracer. It can be set manually by the user.
* By default, instrumentation reports to our tracer, to avoid possible duplicate instrumentation. It can be changed manually by the user.

### CODE REVIEW

**Comment by tonyredondo** [comment]
so custom opentracing spans created by the client won't be created on our tracer by default?, this is what we want?

**Comment by fermayo** [comment]
> so custom opentracing spans created by the client won't be created on our tracer by default?, this is what we want?

I think so. If they have custom opentracing instrumentation, they should be ok with adding `opentracing.SetGlobalTracer(scopeagent.GlobalAgent().Tracer())`, because we could be overwriting their production tracer.

**Comment by tonyredondo** [comment]
> > so custom opentracing spans created by the client won't be created on our tracer by default?, this is what we want?
> 
> I think so. If they have custom opentracing instrumentation, they should be ok with adding `opentracing.SetGlobalTracer(scopeagent.GlobalAgent().Tracer())`, because we could be overwriting their production tracer.

I thought it would be safe to set the tracer at `scopeagent.Run` func, because is only running on `Testing` so we don't mess with production code, at least by default.

In child process context I'm ok with the manual configuration of the tracer.

**Comment by fermayo** [comment]
> I thought it would be safe to set the tracer at `scopeagent.Run` func, because is only running on `Testing` so we don't mess with production code, at least by default.

That seems like too much magic to me... If our instrumentation uses our tracer by default, the only thing we are missing by not setting our tracer as the global tracer is any custom opentracing instrumentation of the user, which doesn't seem like the normal case for someone that will use the defaults anyway. In my opinion, we should blind our instrumentation to work in any case, and optionally integrate with opentracing/opentelemetry/any other tracing system we could benefit from.

**Pull request merged**
