### PR TITLE
Use random pool to generate opentracing IDs

### PR DESCRIPTION
**Pull request by drodriguezhdez**
This `PR` changes the way of generating random opentracing IDs to use a random pool, which improves the spread when random are obtained across multiple goroutines.

### CODE REVIEW

**Comment by tonyredondo** [comment]
I don't think this implementation could help improve the collision problem, It seems to help with concurrency and performance of the concurrency due the `pool + mutex` of different rands. But nothing about collision. 

Maybe we can do a collision tests with this implementation vs normal `math/rand` and vs `crypto/rand`. I think the `crypto/rand` implementation would have fewer collisions.

Beside using a better random generator, the problem will not be solved using this number of bits in the Id, In the backend the tests executions and span count keep growing, so the probability of a collision keeps increasing... I don't know if the backend could have a composed primary key, like traceId + parentSpanId + spanId. This could reduce the probability of a collision drastically.

What do you think @fermayo

**Comment by fermayo** [comment]
Apart from what we can do in the backend, we are having an abnormally high collision rate of span IDs in the case of the Go agent.

**Comment by tonyredondo** [comment]
> Apart from what we can do in the backend, we are having an abnormally high collision rate of span IDs in the case of the Go agent.

Across the same traceId? Because this also will not help in differents `packages/modules`

In the same process I guess I prefer the crypto implementation, less code changes... https://golang.org/pkg/crypto/rand/

**Comment by tonyredondo** [comment]
The better is to create a test comparing all the random generators and select the one with fewer collisions.... I guess

**Comment by drodriguezhdez** [comment]
@tonyredondo you're right, this PR seems does not improve the collision rate, it's just for performance. My bad.

Regarding using `crypto/rand`, I have my doubts because of the additional overhead that could suppose that to the agent. 

Let's check it in that test you mentioned

**Comment by drodriguezhdez** [comment]
Closed due to #223

**Pull request closed without merging**
