### PR TITLE
Adds Go check support

### PR DESCRIPTION
**Pull request by tonyredondo**
This PR adds support for go check framework, instrument the suites and the log funcs. Also support ITR and runner retries.

https://shared.scope.dev/dashboard/8cee2622-8772-4338-8d72-63653e0e0239/2205d752-62a8-45e8-b12d-5b40f3cc4c71/default/explore/inspect/7a74b0737151106c38e38094de7e9c07ed007f0b/

image

image

image

### CODE REVIEW

**Comment by tonyredondo** [comment]
`go-git` instrumented with scope.

- **Normal Execution:** https://shared.scope.dev/dashboard/e310eea2-1592-4b60-8d48-9aa96475e174/5f99ce3b-2ef6-44a2-9a53-d0e66ac0bff1/default/explore/inspect/3d982042aa5a808a235539d4ce70f0ddaebc4283/
- **ITR the second execution:** https://shared.scope.dev/dashboard/e310eea2-1592-4b60-8d48-9aa96475e174/5f99ce3b-2ef6-44a2-9a53-d0e66ac0bff1/default/explore/inspect/d18cc509edecd26e41dbc3e48d965c0998a6e01b/

**Comment by drodriguezhdez** [comment]
Checking with Benchmarks, it seems there are no benchmarks tags. It is benchmark tests supported? Should I add something to the code to enable benchmarks?

```
import (
	. "gopkg.in/check.v1"
	"testing"

	_ "go.undefinedlabs.com/scopeagent/autoinstrument"
)

func Test(t *testing.T) { TestingT(t) } // Step 2

type TestSuite struct{} // Step 3

var _ = Suite(&TestSuite{}) // Step 4

func (s *TestSuite) BenchmarkLogic(c *C) {
	for i := 0; i < c.N; i++ {
		c.Assert("asd", Equals,"asd")
	}
}
```

Command:
```
$ go test -gocheck.b
```

image

**Comment by tonyredondo** [comment]
You're right, Benchmark instrumentation is missing.... I don't know if it's better in a next PR, because this one is quite big already. What do you think? @drodriguezhdez

**Comment by drodriguezhdez** [comment]
Sure. Let's go for other PR for Benchmarks.

**Pull request merged**
